# Generated by Django 6.0.5 on 2026-07-06 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0002_note_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="note",
            options={"ordering": ["-created_at"]},
        ),
    ]
